### ISSUE TITLE
[sti-java-centos7] user not numeric and withing the range error

### ISSUE THREAD

**Issue by dsimansk** [fabric8io/base-images#1]
Hi,
I'm seeing the following error message when trying to use `sti-java-centos7` image on OSE v3.0.1.900

```
I0909 04:04:12.435964       1 sti.go:74] The value of ALLOWED_UIDS is [1-]
I0909 04:04:12.524584       1 docker.go:228] Pulling image fabric8/sti-java-centos7:latest
I0909 04:04:48.449198       1 sti.go:96] Creating a new S2I builder with build config: "Builder Image:\t\tfabric8/sti-java-centos7:latest\nSource:\t\t\thttp://gitlab.xpaasqe.redhat.com/ose3/camel.git\nOutput Image Tag:\t172.30.132.177:5000/dsimansk/jms-quickstart-image:latest\nEnvironment:\t\tOPENSHIFT_BUILD_NAMESPACE=dsimansk,OPENSHIFT_BUILD_SOURCE=http://gitlab.xpaasqe.redhat.com/ose3/camel.git,OUTPUT_DIR=/opt/jboss/source/jms-quickstart/target/,MAVEN_ARGS=package -pl jms-quickstart -am dependency:copy-dependencies -DskipTests -e,OPENSHIFT_BUILD_NAME=jms-quickstart-build-1\nIncremental Build:\tdisabled\nRemove Old Build:\tdisabled\nForce Pull:\t\tdisabled\nQuiet:\t\t\tdisabled\nLayered Build:\t\tdisabled\nDocker Endpoint:\tunix:///var/run/docker.sock\n"
I0909 04:04:48.462561       1 docker.go:211] Image fabric8/sti-java-centos7:latest available locally
F0909 04:04:48.515872       1 builder.go:47] Build error: image "fabric8/sti-java-centos7:latest" must specify a user that is numeric and within the range of allowed users
```

**Comment by rhuss** [comment]
Thanks, will fix that ASAP (today). Recent OpenShift version requires a fixed, numeric user id.

**Comment by dsimansk** [comment]
Great, thanks!

**Comment by dsimansk** [comment]
Hi @rhuss, I've seen your commit https://github.com/fabric8io/base-images/commit/3e8280d51f38e830cd3478db71f65ff59b46e1c7, which should fix the issue. Do you mind kick-off a new image build manually, it seems the push didn't trigger automated build.

Thanks in advance

**Comment by rhuss** [comment]
Yeah, can push it but have still issues testing it myself --> https://github.com/openshift/origin/issues/4625

Will push a 'latest' nevertheless and will let you know.

**Comment by rhuss** [comment]
Just triggered a build --> https://hub.docker.com/r/fabric8/sti-java-centos7/builds/

**Comment by dsimansk** [comment]
The user id is OK now. But I'm getting error upon building dependency path. Something like `mkdir -p ${output_dir}/run-classpath`?

```
I0911 06:53:12.561435       1 sti.go:406] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.8:build-classpath (default-cli) on project fuse-parent: Error while writting to classpath file '/opt/jboss/source/jms-quickstart/target/run-classpath': java.io.FileNotFoundException: /opt/jboss/source/jms-quickstart/target/run-classpath (No such file or directory) -> [Help 1]

```

**Comment by rhuss** [comment]
how did you manage to run it ? Don't you run in this error mentioned above, too ?

Hm, target should be already created because https://github.com/fabric8io/base-images/blob/master/sti/images/centos7/sti/assemble#L116-L120 comes after the build (which creates the `target` dir already). With which environment variables do you trigger the build (so that I can reproduce it, too) ?
