### ISSUE TITLE
Include agent-bond in all images

### ISSUE THREAD

**Issue by jimmidyson** [fabric8io/base-images#14]
Right now we don't include agent bond in centos images, I guess due to productisation issues? We should now include agent bond so we get Prometheus metrics regardless of base image used.

**Comment by jimmidyson** [comment]
Hmm it is included but agent bond is not being used, only jolokia.

**Comment by rhuss** [comment]
which image do you mean specifically ?

**Comment by jimmidyson** [comment]
Ah wait it's the jboss base images. Any problem with me adding agent-bond-opts the same as we do with the other images?

**Comment by rhuss** [comment]
there was a reason that agent-bond is not in the jboss images. will check that later, but probably due to productisation.

**Comment by rhuss** [comment]
will check that (and will also do an overhaul of the complete image stuff).

**Comment by jimmidyson** [comment]
For now I'm going to add in agent-bond-opts to jboss images. We are going to use the JMX exporter for metrics anyway, even if it's hawkular or other pulling in the metrics.

**Comment by rhuss** [comment]
i'm fine with that.

**Comment by jimmidyson** [comment]
Cool thanks.

**Comment by rhuss** [comment]
going to move it to fabric8-images and maybe integrate the s2i stuff here as well for the java base images (the appserver stuff will be separate) soon, too. feel free to play around as you like :)
